### ISSUE TITLE
 Failed to resolve import "vite-plugin-node-polyfills/shims/buffer"

### ISSUE THREAD

**Issue by OliverWich** [davidmyersdev/vite-plugin-node-polyfills#81]
When using a version higher than 0.17.0, and polyfilling a bunch of stuff (see vite config snippet below), I get the following error:
![image](https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/35409274/d9881d1e-b4f8-4b4e-9373-8e56a4782645)

The relevant section of my vite config is this:
```json5
"plugins": [
// ...
 nodePolyfills({
      globals: {
        Buffer: true,
        global: true,
        process: true,
      },
      include: [
        'fs',
        'path',
        'crypto',
        'stream',
        'util',
        'http',
        'https',
      ],
    }),
// ...
]
``` 

With this config everything works fine in 0.17.0 but in the testet versions 0.19.0 and 0.21.0 the error occurs

When trying to include "buffer" in the `include` array, it also fails because there is no polyfill for it (or it gets already polyfilled by the globals section above).
(` ERROR: [plugin: node-stdlib-browser-alias] Cannot find module 'vite-plugin-node-polyfills/shims/buffer' from '.'`)

**Comment by shellscape** [comment]
Just got bit by this one on v0.21.0 @davidmyersdev this is a gnarly regression, could we get a fix in por favor?

**Comment by raduciobanu22** [comment]
Similar issue here

**Comment by choiwonpyo** [comment]
Hello, also, I got same issue. I accepted my senior's comment. just change version to "0.17.0". 
And it works. Thank you bros.

**Comment by choiwonpyo** [comment]
Um... Something happens.

I can build with latest version. (not 0.17.0) when I add "vite-plugin-node-polyfills" at the "top-level" of monorepo.

my projectstatus is.

- Using yarn berry. (PnP zero install)
- monorepo
  - apps/~
  - packages/~
- apps/client using "vite"
- using turborepo for managing 'monorepo'

before "vite", I was developing with "cra".

Because I'm amature yet, I can not pick the reason why this situation happens...

- As Above comment, And scan that repo, pnpm user seems to have Same issue. (not only yarn berry)


### Situation

- 1. I just "yarn add -D ~" at the "top level of monorepo" by mistake.
- 2. After, I  move to "apps/client" dir, And command "yarn add -D ~".
- 3. two package.json file has "vite-plugin-node-polyfills" dependency.
- 4. yarn turbo build. -> client build successfully. 
- 5. "why success??" -> I just remove the top level dependency. and yarn install at the top level.
- 6. -> fail.

After that experience, I have some test.

I don't know why this solve the problem...
- monorepo top level dependency, solve the problem.

**Comment by tommymarshall** [comment]
Running into this issue as well -- it occurs from within a lerna repo and a common package is referencing Buffer (but not using vite).

**Comment by 17Amir17** [comment]
> Hello, also, I got same issue. I accepted my senior's comment. just change version to "0.17.0". And it works. Thank you bros.

This

**Comment by KateAstrid** [comment]
Changing the version to 0.17.0 helps me as well. Thank you @raduciobanu22 🙏

**Comment by davidmyersdev** [comment]
I wasn't able to reproduce this error with just the config provided above. I'll need a StackBlitz or CodeSandbox example in order to diagnose the issue and get a fix together.

**Comment by blake-regalia** [comment]
Happens for me when polyfilling crypto on v0.22.0, and the import comes from the ethers package:
```
Rollup failed to resolve import "vite-plugin-node-polyfills/shims/global" from "app/node_modules/ethers/lib.esm/crypto/crypto-browser.js".
```

As with others, downgrading to v0.17.0 resolves the issue.

**Comment by Flamenco** [comment]
Same here. Using Quasar/Vite.  Needed to go back to version ~0.17.0

**Comment by GiovaniGuizzoYUB** [comment]
Going back to v0.17.0 clears the error Buffer error, but gives me this:

```log
TypeError: Cannot destructure property 'Uint8Array' of 'globalThis' as it is undefined.
    at node_modules/.pnpm/buffer@6.0.3_patch_hash=zkkuxompt5d553skpnegwi5wuy/node_modules/buffer/index.js (helpers.ts:226:31)
    at __require (helpers.ts:13:60)
    at shims/dist/index.js (helpers.ts:1919:46)
    at __init (helpers.ts:10:66)
    at shims/banner/index.cjs (helpers.ts:1927:13)
    at __require (helpers.ts:13:60)
    at helpers.ts:1933:5
    at helpers.ts:1934:3
```

Also, I would like to note that this error and the Buffer not foun only occur in `vite dev`. The built application works as expected.

**Comment by GiovaniGuizzoYUB** [comment]
For those of you coming here with a problem with Buffer or any other polyfill, maybe this will help you:

> Import the plugin before your react or vue plugin in the Vite config file. For some reason, if I import it after, it won't work.

So this will work:

```typescript
plugins: [nodePolyfills(), react(), TanStackRouterVite()],
```

but this won't:

```typescript
plugins: [react(), TanStackRouterVite(), nodePolyfills()],
```

**Comment by OliverWich** [comment]
We've just updated to 0.22.0 and using `nodePolyfills()` as the _first_  vite plugin as @GiovaniGuizzoYUB suggested seems to work fine. (And makes a ton of sense if you think about it :D)

I'll close this now, as it is fixed for us, but for some, downgrading to 0.17.0 might still be a valid "fix".

**Comment by Flamenco** [comment]
With Quasar, including the plugin v 0.22 first still does not work.


quasar.config.ts
```ts
{
  vitePlugins: [
  [nodePolyfills, {include: ['buffer', 'path']}, {server: false}],
   // ...
}
```

```text
[vite]: Rollup failed to resolve import "vite-plugin-node-polyfills/shims/buffer" from "/Users/steven/dev/projects/ct/ct-urm/src/v3/plugins/resource/platformResourceProvider.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

**Comment by Flamenco** [comment]
I was able to fix this by monkey-patching the Vite plugin

```ts
const nodePolyfillsFix = (options?: PolyfillOptions | undefined): Plugin => {
  const origPlugin = nodePolyfills(options)
  return {
    ...origPlugin,
    resolveId(this, source: string, importer: (string | undefined), opts: any) {
      const m = /^vite-plugin-node-polyfills\/shims\/(buffer|global|process)$/.exec(source)
      if (m) {
        return `node_modules/vite-plugin-node-polyfills/shims/${m[1]}/dist/index.cjs`
      } else {
        if (typeof origPlugin.resolveId === 'function') {
          return origPlugin.resolveId.call(this, source, importer, opts)
        }
      }
    }
  }
}

```

Or more simply because the plugin does not currently define  `resolveId`.
```ts
const nodePolyfillsFix = (options?: PolyfillOptions | undefined): Plugin => {
  return {
    ...nodePolyfills(options),
    resolveId(source: string) {
      const m = /^vite-plugin-node-polyfills\/shims\/(buffer|global|process)$/.exec(source)
      if (m) {
        return `node_modules/vite-plugin-node-polyfills/shims/${m[1]}/dist/index.cjs`
      }
    }
  }
}

```

**Comment by BenjaminPiette** [comment]
For me the problem was:
- I had a monorepo with a frontend/ sub-folder.
- frontend was the react app with the vite config.
- frontend was using "axios" in code, with some "import 'axios'", but forgot to add axios as dependency in my frontend.
- as a consequence, it found axios in the parent node_modules, thus the mess happened with polyfills.

Solution:
- `yarn add axios`fro, the frontend folder.

**Comment by SSTPIERRE2** [comment]
@BenjaminPiette thanks I had the same issue! SST monorepo "packages" setup where I imported some stuff from packages/features into packages/core caused it. Think I can update the Vite config to get that working.

**Comment by makulov-vlx** [comment]
The error is still in place (also in 0.23.0), here is the solution without patching the plugin. Add to vite.config.ts:

```
    resolve: {
        alias: {
            'vite-plugin-node-polyfills/shims/buffer': path.resolve(
                __dirname,
                'node_modules',
                'vite-plugin-node-polyfills',
                'shims',
                'buffer',
                'dist',
                'index.cjs'
            ),
            'vite-plugin-node-polyfills/shims/global': path.resolve(
                __dirname,
                'node_modules',
                'vite-plugin-node-polyfills',
                'shims',
                'global',
                'dist',
                'index.cjs'
            ),
            'vite-plugin-node-polyfills/shims/process': path.resolve(
                __dirname,
                'node_modules',
                'vite-plugin-node-polyfills',
                'shims',
                'process',
                'dist',
                'index.cjs'
            ),
        },
```

**Comment by crosskpixel** [comment]
![Image](https://github.com/user-attachments/assets/d8d19010-53d0-4051-88e6-d9688b9a7ef5) change to `plugins: [
        react(),
        wasm(),
        topLevelAwait(),
        nodePolyfills(),
    ],` worked for me , my package.json ` "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.7.2",
    "@fortawesome/free-solid-svg-icons": "^6.7.2",
    "@fortawesome/react-fontawesome": "^0.2.2",
    "@journeyapps/wa-sqlite": "^1.2.0",
    "@powersync/kysely-driver": "^1.1.0",
    "@powersync/react": "^1.5.1",
    "@powersync/web": "^1.12.3",
    "@tanstack/react-table": "^8.21.2",
    "axios": "^1.7.9",
    "better-sqlite3": "^11.9.1",
    "bootstrap": "^5.3.3",
    "browser-image-compression": "^2.0.2",
    "bson": "^6.10.3",
    "dayjs": "^1.11.13",
    "echarts": "^5.6.0",
    "echarts-for-react": "^3.0.2",
    "kysely": "^0.27.6",
    "react": "^18.3.1",
    "react-bootstrap": "^2.10.7",
    "react-dom": "^18.3.1",
    "react-icons": "^5.5.0",
    "react-modal": "^3.16.3",
    "react-router-dom": "^7.4.0",
    "react-select": "^5.10.1",
    "styled-components": "^6.1.17",
    "vite-plugin-node-polyfills": "^0.22.0",
    "zustand": "^5.0.3"
  },`

**Comment by slavafomin** [comment]
I'm not sure why this is closed, but the issue still stands. The `resolve.alias` solution works though. There's obviously problems with how files/exports are organized in this package or with how Rollup tries to resolve them.

**Comment by OliverWich** [comment]
Even though this was resolved for us by switching the plugin order so that `vite-plugin-polyfills` is the first, it still seems to be a problem for a bunch of you.

I'll reopen this so that this hopefully comes to a satisfying resolution, but won't be keeping much track myself.

**If you still have this issue, please add reproduction examples so that the maintainers can take a look and find a proper fix for it.**

**Comment by bvandercar-vt** [comment]
> Even though this was resolved for us by switching the plugin order so that `vite-plugin-polyfills` is the first, it still seems to be a problem for a bunch of you.

Yep, I _only_ have this plugin in my config and I still get this issue. @makulov-vlx solution fixes it.

**Comment by bvandercar-vt** [comment]
> The error is still in place (also in 0.23.0), here is the solution without patching the plugin. Add to vite.config.ts:

Here is a more DRY solution:

```typescript
resolve: {
    alias: Object.fromEntries(
        ['buffer', 'global', 'process'].map((k) => [
          `vite-plugin-node-polyfills/shims/${k}`,
          path.resolve(
            `node_modules/vite-plugin-node-polyfills/shims/${k}/dist/index.cjs`
          ),
        ])
      )
  }
```

**Comment by naffarn** [comment]
Just here to note that with Yarn PnP zero-install configuration (not a monorepo), downgrading to 0.17.0 (from 0.23.0) is the only thing I tried that worked for me. 
I was encountering this error:

```
error during build:
[vite]: Rollup failed to resolve import "vite-plugin-node-polyfills/shims/global" from "/path/to/project/.yarn/cache/@vue-shared-npm-3.5.16-41ec6ee39b-242ecc41f4.zip/node_modules/@vue/shared/dist/shared.esm-bundler.js".
This is most likely unintended because it can break your application at runtime.
```

**Comment by bvandercar-vt** [comment]
The only thing that 100% worked for me was **not using this plugin** and instead explicitly specifying in vote config:

```ts
rollupOptions: {
  external: [
    'node:path',
    'node:fs',
    // add other node built-ins as needed
  ]
}

**Comment by davidmyersdev** [comment]
I will attempt (again) to reproduce the issue myself, but the `missing reproduction` label means that a live example of the problem is not attached to this issue (which is still true). I work on this project (among many others) outside of my full-time job, so I only have so much time to dedicate toward investigating these issues.

**Comment by davidmyersdev** [comment]
Still no luck. Regardless of the combination of package managers or scripts I try, I can't get this error to appear. If someone can provide an example with all the files I need to reproduce this (something like `package.json`, `vite.config.ts`, `index.html`, and `main.ts`) along with the script to run (e.g. `vite dev`), then I will happily dig into it.

**Comment by naffarn** [comment]
> Still no luck. Regardless of the combination of package managers or scripts I try, I can't get this error to appear. If someone can provide an example with all the files I need to reproduce this (something like `package.json`, `vite.config.ts`, `index.html`, and `main.ts`) along with the script to run (e.g. `vite dev`), then I will happily dig into it.

Hey @davidmyersdev, I managed to sort out a repro link for you: https://codesandbox.io/p/devbox/5wk398

The command to run is `vite build`

The configuration is yarn@4.9.2, in zero-install mode. i.e. Yarn Plug & Play with global cache disabled. I have also installed the vscode SDK set for yarn.

**Comment by ICJR** [comment]
@davidmyersdev experiencing the same issue using pnpm in a monorepo. 

Context: I use a private helper/wrapper library with my build defaults including this plugin

When I install my helper without this plugin I receive the error, if I install helper + plugin in workspace package, error is gone.  

pnpm doesn't expose dependencies from other packages, if anyone is using this plugin by importing a wrapper library with this package you will receive this error.

**Comment by fregante** [comment]
Can you locate the package in your node_modules? Does it appear at the root?

/node_modules/vite-plugin-node-polyfills/

**Comment by Tobbe** [comment]
Also with the pnp linker it still works with these settings
```yml
nodeLinker: pnp
pnpMode: strict
pnpEnableEsmLoader: true
pnpFallbackMode: dependencies-only
enableGlobalCache: false

packageExtensions:
  "@vue/devtools-core@*":
    dependencies:
      vue: "*"
```

Only when you change `pnpFallbackMode` to `none` does it break.

https://yarnpkg.com/configuration/yarnrc#pnpFallbackMode
> Define whether to allow packages to rely on the builtin PnP fallback mechanism.
>
> Possible values are:
>
> If `all`, all packages can access dependencies made available in the fallback.
> If `dependencies-only` (the default), dependencies will have access to them but not your workspaces.
> If `none`, no packages will have access to them.

**Comment by naffarn** [comment]
> Only when you change `pnpFallbackMode` to `none` does it break.

@Tobbe Thanks for this! I didn't want to go to `node_modules` linker becasue I specifically want the `pnp` linker for the zero-install functionality, but I think this could get me going.

> Can you locate the package in your node_modules? Does it appear at the root?

@fregante No `node_modules` in the set up I'm using, [Yarn PnP](https://yarnpkg.com/features/pnp) uses a different system. That said, `yarn why` shows that no other modules depend on this plugin:
```bash
➜  workspace git:(main) yarn why vite-plugin-node-polyfills
└─ vue-vite@workspace:.
   └─ vite-plugin-node-polyfills@npm:0.24.0 [03125] (via npm:^0.24.0 [03125])
```

**Comment by Tobbe** [comment]
> You may have forked my reproduction link before I actually added a use of `Buffer` to the repo.

It seems I did, yeah. With the updated code it also fails with the node-modules loader

**Comment by naffarn** [comment]
@Tobbe I'm a dumbass, I was missing `@types/node` 🤦

After adding the node types, `vue-tsc` now passes, and there's no need to remove it from the build script.

So yeah, looks like for yarn PnP, just can't have `pnpFallbackMode: none`. Thanks for your help mate. I'll leave my reproduction link with the broken fallback mode just in case the devs are interested in fixing it.

**Comment by OliverWich** [comment]
We are now running into another fun problem using 0.24.0 which seems similar to this one.

When using rollup-based vite, we get the following error:

<img width="594" height="99" alt="Image" src="https://github.com/user-attachments/assets/a2882ab1-b453-49aa-aba1-13eb6194c8b5" />

My guess is that is has something to do with this change in 0.24.0:
https://github.com/davidmyersdev/vite-plugin-node-polyfills/commit/ca49ba3e5222bd21abb2c76d01a2ce8f072b03a0#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R206-R214

The error goes away when using 

<img width="315" height="294" alt="Image" src="https://github.com/user-attachments/assets/44f0be17-f3bd-41cf-82cd-b689c601b7cd" />

but then the buffer polyfill is obviously not loaded.

We are using
```
    "vite": "npm:rolldown-vite@^7.0.8",
    "vite-plugin-node-polyfills": "0.24.0",
    "vue": "3.5.13",
```

All of this summarizes to:
- using `buffer` in the "includes" array still results in the original error is issue is about with 0.24.0
- NOT using `buffer` in "includes" but having it polyfilled by the default `globals` option works _for us_
- Using rollup based vite, we get another error, also related to importing the buffer polyfill
- Explicitly NOT polyfilling buffer (both by not including it and by setting it to false in the `globals` option) at least does not break anymore, but then the polyfill is obviously missing.
  - On another note, when using `Buffer: false`, we had to also set `global: false` and  `process: false`, otherwise those would fail with the exact same error that buffer failed ("Cannot access lexical definition of __process_polyfill before initialization")


----

Edit:

We gave up.

We could not get any combination of rolldown vite with manual polyfill / polyfills from this plugin to work.
In the end, we just swapped out the few dependencies that needed polyfills to modern equivalents (and actually the big one `opencv-js` just needed a new way of initializing it to not depend on any polyfills anymore).

Now everything works and builds as expected, even without this plugin at all.


Nevertheless, big respect and thanks for the (admittedly very hard) work of the creators/maintainers of this package, I can't imagine it being much fun supporting things that where never meant to work in the first place :D

**Comment by jclab-joseph** [comment]
+1

**Comment by KolissnikBogdan** [comment]
Try to add this to vite.config:

```
imports.....
const require = createRequire(import.meta.url);
const nodePolyfillShims = {
    buffer: require.resolve('vite-plugin-node-polyfills/shims/buffer'),
    global: require.resolve('vite-plugin-node-polyfills/shims/global'),
    process: require.resolve('vite-plugin-node-polyfills/shims/process'),
};

...

export default defineConfig(({
            command,
            mode
        }) => {
            ...
            const polyfillAliases = isBuild ?
                [{
                        find: 'vite-plugin-node-polyfills/shims/buffer',
                        replacement: nodePolyfillShims.buffer,
                    },
                    {
                        find: 'vite-plugin-node-polyfills/shims/global',
                        replacement: nodePolyfillShims.global,
                    },
                    {
                        find: 'vite-plugin-node-polyfills/shims/process',
                        replacement: nodePolyfillShims.process,
                    },
                ] :
                [];

            return {
                ....
                resolve: {
                    alias: [
                        ....
                        ...polyfillAliases,
                    ]
                }
            }
```
